In [1]:
%config IPCompleter.greedy=True

In [2]:
import pandas as pd

df_train = pd.read_csv('train_kaggle.csv')
df_train

          Id  label
0          0      0
1          1      0
2          2      0
3          3      0
4          4      0
5          5      0
6          6      0
7          7      0
8          8      1
9          9      0
10        10      1
11        11      0
12        12      0
13        13      0
14        14      1
15        15      0
16        16      0
17        17      1
18        18      0
19        19      0
20        20      0
21        21      1
22        22      0
23        23      0
24        24      0
25        25      0
26        26      0
27        27      1
28        28      0
29        29      0
...      ...    ...
30306  30306      0
30307  30307      0
30308  30308      0
30309  30309      0
30310  30310      0
30311  30311      0
30312  30312      0
30313  30313      0
30314  30314      0
30315  30315      0
30316  30316      0
30317  30317      0
30318  30318      0
30319  30319      0
30320  30320      0
30321  30321      1
30322  30322      0
30323  30323      0
30324  30324      0
30325  30325      0
30326  30326      0
30327  30327      0
30328  30328      0
30329  30329      0
30330  30330      0
30331  30331      0
30332  30332      0
30333  30333      1
30334  30334      0
30335  30335      1

[30336 rows x 2 columns]

In [4]:
import numpy as np
df_train_all = np.load('df_train_all.npy',allow_pickle=True)

In [5]:
y = df_train['label'].values
y

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [19]:
indices = [22]
# pd_train = pd.DataFrame(df_train_all[0])
# pd_train[pd_train.columns[indices]]

            22
0    95.333333
1    95.333333
2    95.333333
3   100.000000
4    95.333333
5    95.333333
6    95.333333
7    95.333333
8    95.333333
9    95.333333
10   86.000000
11   95.333333
12   95.333333
13   95.333333
14   95.333333
15   95.333333
16   90.000000
17   95.333333
18   95.333333
19   95.333333
20   95.333333
21   95.333333
22   95.333333
23   96.000000
24   95.333333
25   95.333333
26   95.333333
27   95.333333
28   95.333333
29   95.333333
30   95.333333
31   95.333333
32   95.333333
33   95.333333
34   95.333333
35   95.333333
36   95.333333
37   95.333333
38  100.000000
39   95.333333
40   95.333333
41   95.333333
42   95.333333
43  100.000000
44   95.333333
45   95.333333
46   95.333333
47   95.333333
48   95.333333
49   95.333333
50   95.333333
51   95.333333
52   95.333333
53   95.333333

In [48]:
import pandas as pd

def tsfresh_prep(df_x_all):
    data = []
    for i in range(len(df_x_all)):
        pd_x = pd.DataFrame(df_x_all[i])
        pd_x = pd_x[pd_x.columns[indices]]
        pd_x["Id"] = i
        data.append(pd_x)
    return pd.concat(data, ignore_index=True)

In [51]:
pd_train_all = tsfresh_prep(df_train_all)
pd_train_all

                 22     Id
0         95.333333      0
1         95.333333      0
2         95.333333      0
3        100.000000      0
4         95.333333      0
5         95.333333      0
6         95.333333      0
7         95.333333      0
8         95.333333      0
9         95.333333      0
10        86.000000      0
11        95.333333      0
12        95.333333      0
13        95.333333      0
14        95.333333      0
15        95.333333      0
16        90.000000      0
17        95.333333      0
18        95.333333      0
19        95.333333      0
20        95.333333      0
21        95.333333      0
22        95.333333      0
23        96.000000      0
24        95.333333      0
25        95.333333      0
26        95.333333      0
27        95.333333      0
28        95.333333      0
29        95.333333      0
...             ...    ...
1169662    0.000000  30334
1169663    0.000000  30334
1169664    0.000000  30334
1169665    0.000000  30334
1169666    0.000000  30334
1169667    0.000000  30334
1169668    0.000000  30334
1169669    0.000000  30334
1169670    0.000000  30334
1169671    0.000000  30334
1169672    0.000000  30334
1169673    0.000000  30334
1169674    0.000000  30334
1169675    0.000000  30334
1169676    0.000000  30334
1169677    0.000000  30334
1169678    0.000000  30334
1169679    0.000000  30334
1169680    0.000000  30334
1169681    0.000000  30334
1169682    0.000000  30334
1169683    0.000000  30334
1169684    0.000000  30335
1169685    0.000000  30335
1169686    0.000000  30335
1169687    0.000000  30335
1169688    0.000000  30335
1169689    0.000000  30335
1169690    0.000000  30335
1169691    0.000000  30335

[1169692 rows x 2 columns]

In [52]:
from tsfresh import extract_features

extracted_features = extract_features(pd_train_all, column_id="Id")
extracted_features

Feature Extraction: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 50/50 [07:10<00:00,  8.61s/it]

variable,22__abs_energy,22__absolute_sum_of_changes,"22__agg_autocorrelation__f_agg_""mean""__maxlag_40","22__agg_autocorrelation__f_agg_""median""__maxlag_40","22__agg_autocorrelation__f_agg_""var""__maxlag_40","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""intercept""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""rvalue""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""slope""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""stderr""","22__agg_linear_trend__f_agg_""max""__chunk_len_50__attr_""intercept""",...,22__symmetry_looking__r_0.9,22__symmetry_looking__r_0.9500000000000001,22__time_reversal_asymmetry_statistic__lag_1,22__time_reversal_asymmetry_statistic__lag_2,22__time_reversal_asymmetry_statistic__lag_3,22__value_count__value_-1,22__value_count__value_0,22__value_count__value_1,22__variance,22__variance_larger_than_standard_deviation
id,,,,,,,,,,,,,,,,,,,,,
0,490957.333333,58.666667,-0.020578,2.490476e-28,0.033253,98.158730,-0.116527,-0.152381,0.649391,100.000000,...,1.0,1.0,2.238756e-12,-1.738033e+03,-1810.450617,0.0,0.0,0.0,3.358025e+00,1.0
1,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,23.0,0.0,0.000000e+00,0.0
2,74896.500000,6.000000,-0.030000,0.000000e+00,0.035100,40.400000,-0.707107,-0.300000,0.173205,NaN,...,1.0,1.0,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,9.375000e-02,0.0
3,53629.000000,8.000000,-0.022516,0.000000e+00,0.013688,44.666667,-0.866025,-1.000000,0.577350,NaN,...,1.0,1.0,0.000000e+00,-3.027200e+02,-329.043478,0.0,0.0,0.0,2.758621e-01,0.0
4,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,48.0,0.0,0.000000e+00,0.0
5,37553.000000,0.000000,0.000000,0.000000e+00,0.000000,47.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
6,34876.600000,33.600000,-0.013592,2.250566e-29,0.007025,32.800000,-0.719918,-1.660000,0.923977,NaN,...,1.0,1.0,-3.263295e+02,-1.893926e+02,-199.105026,0.0,0.0,0.0,2.195556e+00,1.0
7,32076.000000,53.250000,0.006101,0.000000e+00,0.742830,34.325000,-0.571690,-1.675000,1.699816,NaN,...,1.0,1.0,-2.475000e+02,-3.813750e+02,-446.995864,0.0,0.0,0.0,3.837500e+00,1.0
8,582291.447940,462.382979,0.002087,-2.729990e-03,0.004675,53.207219,-0.282873,-0.243157,0.168298,66.452381,...,1.0,1.0,-7.776536e+01,-1.216928e+03,-1225.259766,0.0,0.0,0.0,1.179692e+01,1.0
9,34560.687500,15.250000,-0.025567,0.000000e+00,0.008750,42.291667,-0.866025,-2.125000,1.226869,NaN,...,1.0,1.0,2.446094e+02,5.269959e+02,-187.624081,0.0,0.0,0.0,1.076087e+00,1.0
10,43464.875000,7.000000,-0.345030,0.000000e+00,3.483322,35.725000,0.932673,0.475000,0.129904,NaN,...,1.0,1.0,3.128125e+02,3.336667e+02,357.500000,0.0,0.0,0.0,3.161765e-01,0.0
11,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,21.0,0.0,0.000000e+00,0.0
12,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,39.0,0.0,0.000000e+00,0.0
13,71245.462810,57.272727,-0.048532,0.000000e+00,0.022098,43.672727,-0.233500,-0.272727,0.655702,NaN,...,1.0,1.0,-2.625074e+01,1.126947e+03,1183.460253,0.0,0.0,0.0,4.120130e+00,1.0
14,15042.333333,2.666667,-0.046204,1.167514e-27,0.015265,32.000000,-1.000000,-0.333333,0.000000,NaN,...,1.0,1.0,-5.169516e+01,-1.228114e+02,-2.345679,0.0,0.0,0.0,4.444444e-02,0.0
15,23576.560000,16.200000,-0.031439,3.198223e-29,0.007978,39.000000,-1.000000,-3.800000,0.000000,NaN,...,1.0,1.0,-7.149195e+02,-1.996123e+02,-106.321231,0.0,0.0,0.0,1.831579e+00,1.0
16,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,37.0,0.0,0.000000e+00,0.0
17,299288.875000,42.750000,0.007287,0.000000e+00,0.002762,48.057143,0.041400,0.015934,0.111011,48.708333,...,1.0,1.0,-2.547070e+02,-2.586256e+02,-262.666626,0.0,0.0,0.0,9.365672e-01,0.0
18,87119.250000,48.083333,-0.030796,0.000000e+00,0.030469,44.350000,0.080666,0.083333,0.594496,NaN,...,1.0,1.0,-2.706266e+02,-2.484162e+02,-130.424934,0.0,0.0,0.0,1.644097e+00,1.0
19,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,19.0,0.0,0.000000e+00,0.0
20,78033.000000,0.000000,0.000000,0.000000e+00,0.000000,37.000000,0.000000,0.000000,0.000000,37.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
21,33314.360000,40.600000,-0.019448,-1.144841e-15,0.103938,47.000000,-1.000000,-3.000000,0.000000,NaN,...,1.0,1.0,1.109520e+03,1.257455e+03,-1478.563692,0.0,0.0,0.0,6.147368e+00,1.0
22,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,21.0,0.0,0.000000e+00,0.0
23,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,51.0,0.0,0.000000e+00,0.0
24,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,50.0,0.0,0.000000e+00,0.0
25,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,13.0,0.0,0.000000e+00,0.0
26,0.000000,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,10.0,0.0,0.000000e+00,0.0
27,63807.000000,152.000000,-0.078394,0.000000e+00,0.058327,59.000000,-0.774597,-6.000000,3.464102,NaN,...,1.0,1.0,-1.017931e+03,-2.008889e+03,-6363.200000,0.0,0.0,0.0,3.329032e+01,1.0
28,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,48.0,0.0,0.000000e+00,0.0
29,67721.812500,46.500000,-0.027368,0.000000e+00,0.015931,43.700000,-0.707107,-1.650000,0.952628,NaN,...,1.0,1.0,-6.407780e+02,-9.973742e+02,-1168.545673,0.0,0.0,0.0,3.366667e+00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30306,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,40.0,0.0,0.000000e+00,0.0
30307,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,36.0,0.0,0.000000e+00,0.0
30308,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,38.0,0.0,0.000000e+00,0.0
30309,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,16.0,0.0,0.000000e+00,0.0
30310,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,36.0,0.0,0.000000e+00,0.0
30311,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,67.0,0.0,0.000000e+00,0.0
30312,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,16.0,0.0,0.000000e+00,0.0
30313,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,42.0,0.0,0.000000e+00,0.0
30314,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,11.0,0.0,0.000000e+00,0.0
30315,68518.640000,32.800000,-0.015595,1.316663e-28,0.009459,38.247619,-0.438356,-0.605714,0.620976,42.000000,...,1.0,1.0,0.000000e+00,0.000000e+00,0.933333,0.0,0.0,0.0,1.503704e+00,1.0
30316,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,51.0,0.0,0.000000e+00,0.0
30317,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,14.0,0.0,0.000000e+00,0.0
30318,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,41.0,0.0,0.000000e+00,0.0
30319,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,49.0,0.0,0.000000e+00,0.0
30320,0.000000,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,10.0,0.0,0.000000e+00,0.0
30321,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,24.0,0.0,0.000000e+00,0.0
30322,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,54.0,0.0,0.000000e+00,0.0
30323,159805.440000,0.000000,0.000000,0.000000e+00,0.000000,54.400000,0.000000,0.000000,0.000000,54.400000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,5.048710e-29,0.0
30324,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,36.0,0.0,0.000000e+00,0.0
30325,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,20.0,0.0,0.000000e+00,0.0
30326,0.000000,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,9.0,0.0,0.000000e+00,0.0
30327,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,39.0,0.0,0.000000e+00,0.0
30328,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,39.0,0.0,0.000000e+00,0.0
30329,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,41.0,0.0,0.000000e+00,0.0
30330,86903.000000,0.000000,0.000000,0.000000e+00,0.000000,43.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
30331,78695.555556,20.000000,-0.016804,0.000000e+00,0.013823,41.800000,-0.649519,-0.600000,0.405518,NaN,...,1.0,1.0,6.063298e-13,6.326920e-13,-97.569024,0.0,0.0,0.0,4.666667e-01,0.0
30332,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,54.0,0.0,0.000000e+00,0.0
30333,68616.937500,34.000000,-0.051965,0.000000e+00,0.077344,48.975000,-0.774597,-2.025000,1.169134,NaN,...,1.0,1.0,-8.621207e+02,-1.179479e+03,-1222.024784,0.0,0.0,0.0,2.421429e+00,1.0
30334,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,46.0,0.0,0.000000e+00,0.0
30335,0.000000,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.0,8.0,0.0,0.000000e+00,0.0

In [53]:
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

impute(extracted_features)
features_filtered = select_features(extracted_features, y)

WARNING:tsfresh.feature_selection.relevance:Infered classification as machine learning task

In [54]:
df_test = pd.read_csv('sample_solution.csv')

In [55]:
df_test_all = np.load('df_test_all.npy',allow_pickle=True)

In [56]:
pd_test_all = tsfresh_prep(df_test_all)
pd_test_all

          22    Id
0       54.0     0
1       51.0     0
2       54.0     0
3       54.0     0
4       57.0     0
5       54.0     0
6       54.0     0
7       54.0     0
8       54.0     0
9       54.0     0
10      54.0     0
11      54.0     0
12      54.0     0
13      54.0     0
14      54.0     0
15      54.0     0
16      54.0     0
17      54.0     0
18      54.0     0
19      54.0     0
20      54.0     0
21      54.0     0
22      54.0     0
23      54.0     0
24      54.0     0
25      54.0     0
26      54.0     0
27      54.0     0
28      54.0     0
29      54.0     0
...      ...   ...
382488   0.0  9999
382489   0.0  9999
382490   0.0  9999
382491   0.0  9999
382492   0.0  9999
382493   0.0  9999
382494   0.0  9999
382495   0.0  9999
382496   0.0  9999
382497   0.0  9999
382498   0.0  9999
382499   0.0  9999
382500   0.0  9999
382501   0.0  9999
382502   0.0  9999
382503   0.0  9999
382504   0.0  9999
382505   0.0  9999
382506   0.0  9999
382507   0.0  9999
382508   0.0  9999
382509   0.0  9999
382510   0.0  9999
382511   0.0  9999
382512   0.0  9999
382513   0.0  9999
382514   0.0  9999
382515   0.0  9999
382516   0.0  9999
382517   0.0  9999

[382518 rows x 2 columns]

In [58]:
extracted_features_test = extract_features(pd_test_all, column_id="Id")
extracted_features_test

Feature Extraction: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 50/50 [02:20<00:00,  2.82s/it]

variable,22__abs_energy,22__absolute_sum_of_changes,"22__agg_autocorrelation__f_agg_""mean""__maxlag_40","22__agg_autocorrelation__f_agg_""median""__maxlag_40","22__agg_autocorrelation__f_agg_""var""__maxlag_40","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""intercept""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""rvalue""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""slope""","22__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""stderr""","22__agg_linear_trend__f_agg_""max""__chunk_len_50__attr_""intercept""",...,22__symmetry_looking__r_0.9,22__symmetry_looking__r_0.9500000000000001,22__time_reversal_asymmetry_statistic__lag_1,22__time_reversal_asymmetry_statistic__lag_2,22__time_reversal_asymmetry_statistic__lag_3,22__value_count__value_-1,22__value_count__value_0,22__value_count__value_1,22__variance,22__variance_larger_than_standard_deviation
id,,,,,,,,,,,,,,,,,,,,,
0,157482.000000,12.000,-0.013235,0.000000e+00,0.006832,55.571429,-0.654654,-0.428571,0.247436,57.000000,...,1.0,1.0,3.271154e+02,340.200000,-0.562500,0.0,0.0,0.0,3.333333e-01,0.0
1,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,40.0,0.0,0.000000e+00,0.0
2,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,48.0,0.0,0.000000e+00,0.0
3,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,57.0,0.0,0.000000e+00,0.0
4,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,47.0,0.0,0.000000e+00,0.0
5,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,18.0,0.0,0.000000e+00,0.0
6,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,19.0,0.0,0.000000e+00,0.0
7,14375.000000,0.000,0.000000,0.000000e+00,0.000000,25.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
8,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,18.0,0.0,0.000000e+00,0.0
9,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,53.0,0.0,0.000000e+00,0.0
10,0.000000,0.000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,8.0,0.0,0.000000e+00,0.0
11,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,24.0,0.0,0.000000e+00,0.0
12,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,26.0,0.0,0.000000e+00,0.0
13,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,44.0,0.0,0.000000e+00,0.0
14,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,47.0,0.0,0.000000e+00,0.0
15,30053.750000,2.000,-0.023359,0.000000e+00,0.019097,28.700000,-0.258199,-0.050000,0.132288,NaN,...,1.0,1.0,0.000000e+00,-24.397727,-25.971774,0.0,0.0,0.0,1.351351e-02,0.0
16,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,24.0,0.0,0.000000e+00,0.0
17,77505.960000,35.800,-0.018997,0.000000e+00,0.011145,46.800000,-0.774597,-1.200000,0.692820,NaN,...,1.0,1.0,-4.262385e+02,-230.610222,-690.424706,0.0,0.0,0.0,1.649000e+00,1.0
18,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,54.0,0.0,0.000000e+00,0.0
19,34064.010000,6.600,-0.027113,3.152546e-28,0.023524,32.805000,-0.774597,-0.495000,0.285788,NaN,...,1.0,1.0,-1.059954e+02,-113.061713,-121.137549,0.0,0.0,0.0,1.601471e-01,0.0
20,101695.000000,0.000,0.000000,0.000000e+00,0.000000,43.000000,0.000000,0.000000,0.000000,43.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
21,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,57.0,0.0,0.000000e+00,0.0
22,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,36.0,0.0,0.000000e+00,0.0
23,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,23.0,0.0,0.000000e+00,0.0
24,84488.750000,2.000,-0.012723,0.000000e+00,0.006313,38.690476,-0.392792,-0.042857,0.050170,39.000000,...,1.0,1.0,4.545455e-03,0.000000,0.000000,0.0,0.0,0.0,8.771930e-03,0.0
25,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,37.0,0.0,0.000000e+00,0.0
26,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,22.0,0.0,0.000000e+00,0.0
27,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,21.0,0.0,0.000000e+00,0.0
28,38025.000000,0.000,0.000000,0.000000e+00,0.000000,39.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
29,28274.700000,0.000,0.000000,0.000000e+00,0.000000,30.700000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,5.048710e-29,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,19.0,0.0,0.000000e+00,0.0
9971,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,46.0,0.0,0.000000e+00,0.0
9972,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,16.0,0.0,0.000000e+00,0.0
9973,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,46.0,0.0,0.000000e+00,0.0
9974,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,26.0,0.0,0.000000e+00,0.0
9975,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,30.0,0.0,0.000000e+00,0.0
9976,129600.000000,0.000,0.000000,0.000000e+00,0.000000,60.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
9977,70304.000000,0.000,0.000000,0.000000e+00,0.000000,52.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
9978,25993.760000,64.800,-0.016841,1.988070e-30,0.006546,27.971429,-0.392792,-1.388571,1.625501,38.000000,...,1.0,1.0,7.807754e+01,132.987040,153.452167,0.0,0.0,0.0,6.125926e+00,1.0
9979,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,56.0,0.0,0.000000e+00,0.0
9980,59952.260000,20.000,-0.014973,5.363188e-29,0.008158,39.240000,-0.707107,-0.780000,0.450333,NaN,...,1.0,1.0,1.732371e-13,-75.704475,-374.263105,0.0,0.0,0.0,9.413636e-01,0.0
9981,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,52.0,0.0,0.000000e+00,0.0
9982,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,22.0,0.0,0.000000e+00,0.0
9983,824086.326531,180.000,0.023129,-2.771360e-18,0.002844,64.563910,0.408234,0.478697,0.259621,62.542857,...,1.0,1.0,1.356675e+02,652.207677,683.127920,0.0,0.0,0.0,8.852484e+00,1.0
9984,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,44.0,0.0,0.000000e+00,0.0
9985,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,36.0,0.0,0.000000e+00,0.0
9986,60918.250977,104.625,-0.014240,0.000000e+00,0.021034,42.562500,-0.033301,-0.100000,1.732754,NaN,...,1.0,1.0,-5.616962e+00,-21.413601,30.009989,0.0,0.0,0.0,1.077096e+01,1.0
9987,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,40.0,0.0,0.000000e+00,0.0
9988,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,39.0,0.0,0.000000e+00,0.0
9989,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,37.0,0.0,0.000000e+00,0.0
9990,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,26.0,0.0,0.000000e+00,0.0
9991,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,47.0,0.0,0.000000e+00,0.0
9992,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,16.0,0.0,0.000000e+00,0.0
9993,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,24.0,0.0,0.000000e+00,0.0
9994,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,14.0,0.0,0.000000e+00,0.0
9995,79007.000000,0.000,0.000000,0.000000e+00,0.000000,41.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.0
9996,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,25.0,0.0,0.000000e+00,0.0
9997,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,49.0,0.0,0.000000e+00,0.0
9998,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,37.0,0.0,0.000000e+00,0.0
9999,0.000000,0.000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000e+00,0.000000,0.000000,0.0,38.0,0.0,0.000000e+00,0.0

In [59]:
XTest = extracted_features_test[features_filtered.columns]
XTest

variable,"22__agg_linear_trend__f_agg_""mean""__chunk_len_50__attr_""stderr""","22__agg_linear_trend__f_agg_""min""__chunk_len_50__attr_""stderr""",22__ratio_beyond_r_sigma__r_7,22__ratio_beyond_r_sigma__r_6,"22__agg_linear_trend__f_agg_""var""__chunk_len_50__attr_""stderr""","22__agg_linear_trend__f_agg_""max""__chunk_len_50__attr_""stderr""",22__number_peaks__n_50,"22__fft_coefficient__coeff_28__attr_""abs""","22__fft_coefficient__coeff_27__attr_""abs""",22__number_cwt_peaks__n_5,...,"22__fft_coefficient__coeff_34__attr_""real""","22__fft_coefficient__coeff_56__attr_""imag""","22__fft_coefficient__coeff_22__attr_""angle""","22__fft_coefficient__coeff_90__attr_""real""","22__fft_coefficient__coeff_72__attr_""angle""","22__fft_coefficient__coeff_96__attr_""abs""","22__fft_coefficient__coeff_63__attr_""imag""","22__fft_coefficient__coeff_61__attr_""angle""","22__fft_coefficient__coeff_25__attr_""angle""","22__fft_coefficient__coeff_95__attr_""abs"""
id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,NaN,6.000000e+00,2.0,...,NaN,NaN,83.333333,NaN,NaN,NaN,NaN,NaN,33.333333,NaN
1,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,0.00000,0.000000e+00,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
4,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
10,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,NaN,0.000000e+00,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
19,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,NaN,2.176754e-14,2.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,19.479063,NaN
21,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,0.00000,0.000000e+00,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
22,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,0.99962,9.965845e-01,2.0,...,NaN,NaN,-67.894737,NaN,NaN,NaN,NaN,NaN,74.210526,NaN
25,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9971,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9972,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9973,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9974,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9975,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9976,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9977,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9978,0.000000,0.000000,0.00000,0.018519,0.000000,0.00000,0.0,NaN,9.600000e+00,3.0,...,NaN,NaN,-12.530472,NaN,NaN,NaN,NaN,NaN,18.261907,NaN
9979,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,0.00000,0.000000e+00,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
9980,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,3.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9981,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
9982,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9983,0.093511,3.612563,0.01087,0.010870,5.263908,2.56857,0.0,16.35166,3.193103e+01,3.0,...,-12.465792,-16.248105,59.732619,-24.156557,-168.665988,NaN,-0.610694,-51.044179,53.889028,NaN
9984,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9985,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9986,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9988,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9989,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9990,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9991,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9992,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9993,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9994,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,1.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,NaN,NaN,0.00000,0.000000,NaN,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
XTest = extracted_features_test[features_filtered.columns]
XTest = XTest.replace([np.inf], np.finfo('float32').max).replace([np.inf, -np.inf], np.finfo('float32').min).fillna(0)
print(np.all(np.isfinite(XTest)))
# XTest

True

In [61]:
import lightgbm as lgb

train_data = lgb.Dataset(features_filtered, label=y)
train_data

In [63]:
param = {'num_leaves': 31, 'objective': 'binary'}
param['metric'] = 'binary_logloss'

In [68]:
num_round = 10
bst = lgb.train(param, train_data, num_round)

In [70]:
bst.save_model('model.txt')

In [73]:
probs = 1 - bst.predict(XTest)
probs

array([0.96391452, 0.94868562, 0.94868562, ..., 0.94868562, 0.94868562,
       0.94868562])

In [78]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform as sp_randFloat
from scipy.stats import randint as sp_randInt

gb_clf = GradientBoostingClassifier()
parameters = {'learning_rate': sp_randFloat(),
                  'subsample'    : sp_randFloat(),
                  'n_estimators' : sp_randInt(100, 1000),
                  'max_depth'    : sp_randInt(4, 10) 
                 }
X_train = features_filtered
y_train = y

randm = RandomizedSearchCV(estimator=gb_clf, param_distributions = parameters, 
                           cv = 2, n_iter = 10, n_jobs=-1)
randm.fit(X_train, y_train)

# Results from Random Search
print("\n========================================================")
print(" Results from Random Search " )
print("========================================================")    

print("\n The best estimator across ALL searched params:\n",
      randm.best_estimator_)

print("\n The best score across ALL searched params:\n",
      randm.best_score_)

print("\n The best parameters across ALL searched params:\n",
      randm.best_params_)

print("\n ========================================================")

========================================================
 Results from Random Search
========================================================

 The best estimator across ALL searched params:
 GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.05391078081887679, loss='deviance',
                           max_depth=4, max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=941,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=0.8270991415312796,
                           tol=0.0001, validation_fraction=0.1, verbose=0,
                           warm_start=False)

 The best score across ALL searched params:
 0.9492022679324894

 The best parameters across ALL searched params:
 {'learning_rate': 0.05391078081887679, 'max_depth': 4, 'n_estimators': 941, 'subsample': 0.8270991415312796}

 ========================================================

In [79]:
gb_clf = GradientBoostingClassifier(learning_rate=0.05391078081887679,
                           max_depth=4, n_estimators=941, subsample=0.8270991415312796)

XTrain = features_filtered
scores = cross_val_score(gb_clf, XTrain, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
scores

Accuracy: 0.95 (+/- 0.00)

array([0.95072512, 0.95187078, 0.9513763 , 0.9513763 , 0.94709082])

In [80]:
gb_clf.fit(XTrain, y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.05391078081887679, loss='deviance',
                           max_depth=4, max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=941,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=0.8270991415312796,
                           tol=0.0001, validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [81]:
res = probs

In [82]:
df_test['Predicted'] = res
df_test

        Id  Predicted
0        0   0.963915
1        1   0.948686
2        2   0.948686
3        3   0.948686
4        4   0.948686
5        5   0.925172
6        6   0.925172
7        7   0.946766
8        8   0.925172
9        9   0.948686
10      10   0.687347
11      11   0.925172
12      12   0.925172
13      13   0.948686
14      14   0.948686
15      15   0.765543
16      16   0.925172
17      17   0.963915
18      18   0.948686
19      19   0.946045
20      20   0.959527
21      21   0.948686
22      22   0.948686
23      23   0.925172
24      24   0.963915
25      25   0.948686
26      26   0.925172
27      27   0.925172
28      28   0.931926
29      29   0.920506
...    ...        ...
9970  9970   0.925172
9971  9971   0.948686
9972  9972   0.914985
9973  9973   0.948686
9974  9974   0.925172
9975  9975   0.925172
9976  9976   0.956022
9977  9977   0.939124
9978  9978   0.963915
9979  9979   0.948686
9980  9980   0.963915
9981  9981   0.948686
9982  9982   0.925172
9983  9983   0.314413
9984  9984   0.948686
9985  9985   0.948686
9986  9986   0.949944
9987  9987   0.948686
9988  9988   0.948686
9989  9989   0.948686
9990  9990   0.925172
9991  9991   0.948686
9992  9992   0.914985
9993  9993   0.925172
9994  9994   0.915101
9995  9995   0.963915
9996  9996   0.925172
9997  9997   0.948686
9998  9998   0.948686
9999  9999   0.948686

[10000 rows x 2 columns]

In [83]:
df_test.to_csv('test.csv', index=False)